### ISSUE TITLE
Lighty.io responds back success message even if device returns error message

### ISSUE THREAD

**Issue by MuhendisBey** [PANTHEONtech/lighty#954]
**Describe the bug**
The netconf devices return error message as we saw in the screenshot. Then lighty.io response back success message.

**Branch**
lighty.io branch 15.1.0

**To Reproduce**
1. set a leaf by using swagger interface
2. device should return error message
3. see the result

**Expected behavior**
lighty.io should return error message

**Actual behavior**
lighty.io returns success message

**Screenshots**
![image](https://user-images.githubusercontent.com/10077290/163776755-9a8644c5-4c19-4207-9f03-218b4912982a.png)

**Comment by guraybaydur** [comment]
I have the same problem could someone please help?

**Comment by guraybaydur** [comment]
Could someone please look at this issue? It is criticial for our project.

**Comment by PeterSuna** [comment]
Hello,
Apologies for the late response, our current priority is to create lighty release 16.0.0. 
I have tried this with [lighty netconf simulator 15.1.0 toaster example](https://github.com/PANTHEONtech/lighty-netconf-simulator/tree/15.1.0/examples/devices/lighty-toaster-device)  and [lighty-community-restconf-netconf-app example 15.1.0](https://github.com/PANTHEONtech/lighty/tree/15.1.0/lighty-examples/lighty-community-restconf-netconf-app) and everything work fine. I have tried to populate leaf data with POST request. The first request was successful and the second failed due to duplicate data. Notice that on the bottom is expected result and on top is actual response

![Capture](https://user-images.githubusercontent.com/20340119/165932690-27d35ccd-a840-470b-9d3c-1a3620f56b6a.PNG)


I hope this helps.

**Comment by MuhendisBey** [comment]
Hello @PeterSuna 

Thx a lot for investigating.
As you can see, there is a error difference error messages. I got "resource denied" error and you got "data exists" error. Maybe you can try that. Beside, this error is appeared during the abort operation(i guess.) In that case, we can try abort operation at lighty netconf device simulator also we can try another on netconf device such as confd.

Hello @ihrasko 
Can we keep open for a while?

Last but not least, what is the release time of 16.0.0, i'm willing to try it :-)

Many thanks again,
With My best Regards,

**Comment by guraybaydur** [comment]
> Hello @PeterSuna
> 
> Thx a lot for investigating. As you can see, there is a error difference error messages. I got "resource denied" error and you got "data exists" error. Maybe you can try that. Beside, this error is appeared during the abort operation(i guess.) In that case, we can try abort operation at lighty netconf device simulator also we can try another on netconf device such as confd.
> 
> Hello @ihrasko Can we keep open for a while?
> 
> Last but not least, what is the release time of 16.0.0, i'm willing to try it :-)
> 
> Many thanks again, With My best Regards,

Hello @PeterSuna ,

First of all thank you for working on this issue. Did you have a chance to try it as @MuhendisBey suggests like above?

Thank you very much
Regards

**Comment by ugurkaraca3** [comment]
Hello everyone,
This issue tested on 16.0.0, it is solved. Thanks for support.

**Comment by MuhendisBey** [comment]
thx @ugurkaraca3 for your effor. also, according to your effor, it didn't work on v15.2.0. This is additional info.

In any case, we can close this issue @ihrasko .
Many thx for your effor.
